---
language: ruby
sudo: false
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.9.0"
rvm:
  - 2.3
script: ./test.sh
matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.8.0"
  fast_finish: true
